#version 450

#include "lib/sh.glsl"

// -------------------------------- I/O --------------------------------

layout(local_size_x = 1, local_size_y = 1) in;

layout(set = 0, binding = 0) writeonly buffer SHBuffer {
	SH probes[];
};

layout(push_constant) uniform PushConstants {
	uint index;
};


// -------------------------------- MAIN --------------------------------

void main() {
	probes[index] = empty_sh();
}


